name: C2Rust

on: workflow_dispatch

jobs:
  C2Rust:
    runs-on: ubuntu-latest
    env:
      LANG: zh_CN.UTF-8

    steps:
      - name: 终端汉化
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-zh-hans
   
      - name: 安装依赖
        run: |
          sudo apt-get install curl expat gettext openssl zlib1g-dev gcc perl make libssl-dev libcurl4-gnutls-dev libexpat1-dev bear

      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: 安装 C2Rust
        run: |
          cargo install c2rust

      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 创建数据库
        run: |
          bear -- make -j16

      - name: 转换
        run: |
          c2rust transpile compile_commands.json